spring.application.name=api-visitas

server.port=8080

#h2
spring.datasource.url=jdbc:h2:mem:cecytedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


jwt.secret=Y2VjeXRlLWFwaS12aXNpdGFzLXNlY3JldC1rZXktMjAyNi1wcm90b3R5cGU=
jwt.expiration-ms=28800000
